version: '3'

services:
  server:
    build: ./server
    ports:
    - "3000:3000"
    command: npm run start:dev
    volumes:
    - ./server:/app
    - /app/node_modules
    depends_on:
    - neo4j

  neo4j:
    image: neo4j:3.0
    ports:
    - "7473:7473"
    - "7474:7474"
    - "7687:7687"

  client:
    build:
      context: ./client
      args:
      - NODE_ENV=development
    ports:
    - "1233:1233"
    - "1234:1234"
    - "3001:3001"
    - "38771:38771"
    command: npm start
    volumes:
    - ./client:/app
    - /app/node_modules
    environment:
    - NODE_ENV=development
    depends_on:
    - server
